### ISSUE TITLE
Add opacity to Consensus 2018 as the event has already been completed

### ISSUE THREAD

**Issue by jjperezaguinaga** [MyBitFoundation/MyBit.io#106]
Issue

The community page shows an event that happened already.

It should be deleted or have a reduced opacity (to clearly indicate that it is in the past and we were there).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe62046815ee23d54c7dc7e9ddb8dbd7df7942d3199ff2b6857f6e8cc1111c83a](https://etherscan.io/tx/0xe62046815ee23d54c7dc7e9ddb8dbd7df7942d3199ff2b6857f6e8cc1111c83a)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc45286ac864abbd8a7ec1919ee018a2b0c429c9a1c309acdb9356dce60cdf120](https://etherscan.io/tx/0xc45286ac864abbd8a7ec1919ee018a2b0c429c9a1c309acdb9356dce60cdf120)
