### ISSUE TITLE
CSS positioning of the Industries is off

### ISSUE THREAD

**Issue by zaudo** [MyBitFoundation/MyBit.io#64]
The industries box is out of line on desktop browsers. E.g. on Chrome v66.0.3359.181 with a vertical resolution of 1440 at 1:1 scaling, the Industries box is too low:

![chrome_2018-05-29_16-13-18](https://user-images.githubusercontent.com/19153789/40668055-789e020c-635b-11e8-8d05-d461eb04f141.png)

On a low vertical resolution, the Industries box is too high up:

![chrome_2018-05-29_16-13-04](https://user-images.githubusercontent.com/19153789/40668037-73c1bc06-635b-11e8-9487-4565bc965bf9.png)

It should be relative positioned below the above containers and so shouldn't move when scaling.

**Comment by jjperezaguinaga** [comment]
@zaudo thank you for raising this issue! Sadly it's not related on whether is relatively positioned (if you change that it will make the whole website work funky), but on being able to do a more responsive design for that resolution.

Will work on it!

**Comment by jjperezaguinaga** [comment]
We already fixed this in latest release, so closing it down for the time being!
